name: .NET Tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      - name: Build StockSharp.sln (Windows only)
        if: matrix.os == 'windows-latest'
        run: dotnet build StockSharp.sln --configuration Release

      - name: Build
        run: dotnet build StockSharp_Tests.sln --configuration Release

      - name: Run tests
        run: dotnet test StockSharp_Tests.sln --no-build --configuration Release
